apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app:  server
    spec:
      containers:
      - name:  server
        image:  mohsin12435/carparking
        ports:
        - containerPort: 9117
        env:
          - name:  SPRING_DATASOURCE_USERNAME
            value: postgres
          - name:  SPRING_DATASOURCE_PASSWORD
            value: 1
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://10.111.116.122:5432/postgres
